### ISSUE TITLE
Try the qt app

### ISSUE THREAD

**Issue by ManuXD32** [Szybet/sanki#1]
Hi, i've got a kobo nia and i'm willing to try your app, could you please give me a short hint of how to build the app and install it onto de kobo nia? I already have a little knowledge about compiling linux apps so i think i can do it. Thank you so much.

**Comment by Szybet** [comment]
Welcome
thanks for the interest for my app, We talked about it on [discord](https://discord.gg/3Wkeb8gbds) so I think this issue can be closed

An longer comment on this because discord is a knowledge hole: You need inkbox, sanki won't run without heavy modyfications on another OS
